<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
	<ProjectReference Include="..\GitTransformer.Core\GitTransformer.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="BlazorMonaco" Version="3.5.0" />
  </ItemGroup>
</Project>
