name: Deploy to GitHub Pages
env:
  NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches: [ master ]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: '9.0.x'
    - name: Build
      run: dotnet build -c release
    - name: Publish .NET Core Project
      run: dotnet publish GitTransformer/GitTransformer.csproj
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.7.2
      with:
        folder: GitTransformer/bin/Release/net9.0/wwwroot
    - name: Add .nojekyll file
      run: touch GitTransformer/bin/Release/net9.0/wwwroot/.nojekyll
